// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/auth_entity.dart';

class AuthModel extends AuthEntity {
  const AuthModel();

  factory AuthModel.fromJson(Map<String, dynamic> json) {
    return const AuthModel();
  }
}
