// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/shell_entity.dart';

class ShellModel extends ShellEntity {
  const ShellModel();

  factory ShellModel.fromJson(Map<String, dynamic> json) {
    return const ShellModel();
  }
}
