// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../entities/profile_entity.dart';

abstract class ProfileRepository {
  Future<ProfileEntity> get();
}
