// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../entities/auth_entity.dart';
import '../repositories/auth_repository.dart';

class AuthUseCases {
  const AuthUseCases(this.repository);

  final AuthRepository repository;

  Future<AuthEntity> get() {
    return repository.get();
  }
}
