// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../entities/shell_entity.dart';
import '../repositories/shell_repository.dart';

class ShellUseCases {
  const ShellUseCases(this.repository);

  final ShellRepository repository;

  Future<ShellEntity> get() {
    return repository.get();
  }
}
