// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

abstract class ProfileRemoteDataSource {
  Future<Map<String, dynamic>> fetch();
}

/// Placeholder implementation.
///
/// Replace this with the real HTTP/local source when the application
/// defines its data contract.
class ProfileRemoteDataSourceImpl
    implements ProfileRemoteDataSource {
  const ProfileRemoteDataSourceImpl();

  @override
  Future<Map<String, dynamic>> fetch() {
    throw UnimplementedError(
      'ProfileRemoteDataSourceImpl.fetch() has not been implemented.',
    );
  }
}
