// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

abstract class AuthRemoteDataSource {
  Future<Map<String, dynamic>> fetch();
}

/// Placeholder implementation.
///
/// Replace this with the real HTTP/local source when the application
/// defines its data contract.
class AuthRemoteDataSourceImpl
    implements AuthRemoteDataSource {
  const AuthRemoteDataSourceImpl();

  @override
  Future<Map<String, dynamic>> fetch() {
    throw UnimplementedError(
      'AuthRemoteDataSourceImpl.fetch() has not been implemented.',
    );
  }
}
