// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture presentation widget scaffold generated by Galaxy.

import 'package:flutter/material.dart';

class ProfileScreenWidget extends StatelessWidget {
  const ProfileScreenWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox.shrink();
  }
}
