// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/shell_entity.dart';
import '../../domain/repositories/shell_repository.dart';
import '../datasources/shell_remote_data_source.dart';
import '../models/shell_model.dart';

class ShellRepositoryImpl implements ShellRepository {
  const ShellRepositoryImpl(this.dataSource);

  final ShellRemoteDataSource dataSource;

  @override
  Future<ShellEntity> get() async {
    final json = await dataSource.fetch();
    return ShellModel.fromJson(json);
  }
}
