// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/profile_entity.dart';
import '../../domain/repositories/profile_repository.dart';
import '../datasources/profile_remote_data_source.dart';
import '../models/profile_model.dart';

class ProfileRepositoryImpl implements ProfileRepository {
  const ProfileRepositoryImpl(this.dataSource);

  final ProfileRemoteDataSource dataSource;

  @override
  Future<ProfileEntity> get() async {
    final json = await dataSource.fetch();
    return ProfileModel.fromJson(json);
  }
}
