name: example_project_name
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  tokens:
    path: ../../packages/tokens
  design_system:
    path: ../../packages/design_system

flutter:
  uses-material-design: true

  assets:
    - assets/