// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../entities/profile_entity.dart';
import '../repositories/profile_repository.dart';

class ProfileUseCases {
  const ProfileUseCases(this.repository);

  final ProfileRepository repository;

  Future<ProfileEntity> get() {
    return repository.get();
  }
}
