// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

abstract class ShellRemoteDataSource {
  Future<Map<String, dynamic>> fetch();
}

/// Placeholder implementation.
///
/// Replace this with the real HTTP/local source when the application
/// defines its data contract.
class ShellRemoteDataSourceImpl
    implements ShellRemoteDataSource {
  const ShellRemoteDataSourceImpl();

  @override
  Future<Map<String, dynamic>> fetch() {
    throw UnimplementedError(
      'ShellRemoteDataSourceImpl.fetch() has not been implemented.',
    );
  }
}
