// GENERATED FILE - DO NOT EDIT BY HAND.
// Clean Architecture scaffold generated by Galaxy.

import '../../domain/entities/profile_entity.dart';

class ProfileModel extends ProfileEntity {
  const ProfileModel();

  factory ProfileModel.fromJson(Map<String, dynamic> json) {
    return const ProfileModel();
  }
}
